platform :ios, '6.0'

pod 'SSToolkit'
pod 'MALazykit', :head
pod 'MASimplestSemiModalViewController'
pod 'uiview-frame-helpers'
pod 'UIView+EasingFunctions', '~> 0.0.1'
pod 'AHEasing', '~> 1.1'
pod 'UAModalPanel'
pod 'Finch'
pod 'Google-Mobile-Ads-SDK'
pod 'AFNetworking', '~> 1.3.1'
pod 'FontAwesome+iOS'
pod 'SVProgressHUD'
pod 'iRate'
pod 'GoogleAnalytics-iOS-SDK'
